// version.h generated by GEMMA scripts/gen_version_info.sh
#define GEMMA_VERSION "0.98.2"
#define GEMMA_DATE "2020-05-22"
#define GEMMA_YEAR "2020"
#define GEMMA_PROFILE "/gnu/store/h9xwdvc7kqx7cvpvs6iascfdw5zgzhyd-profile"
