// version.h generated by GEMMA scripts/gen_version_info.sh
#define GEMMA_VERSION "0.98.6"
#define GEMMA_DATE "2022-08-05"
#define GEMMA_YEAR "2022"
#define GEMMA_PROFILE "/gnu/store/8rvid272yb53bgascf5c468z0jhsyflj-profile"
