// version.h generated by GEMMA scripts/gen_version_info.sh
#define GEMMA_VERSION "0.98.4"
#define GEMMA_DATE "2020-12-15"
#define GEMMA_YEAR "2020"
#define GEMMA_PROFILE "/gnu/store/8mkllydvkgfy6ydlrymrx8wj0dy1x6lm-profile"
